version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres